version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: ava-user-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: users
    ports:
      - 3306:3306